apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: external-destination-source-3
    name: external-destination-source-3
  name: external-destination-source-3
  namespace: qa
spec:
  minReadySeconds: 15
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: external-destination-source-3
      name: external-destination-source-3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: external-destination-source-3
        deployment: external-destination-source-3
        name: external-destination-source-3
      name: external-destination-source-3
      namespace: qa
    spec:
      imagePullSecrets:
        - name: qa
      containers:
      - args:
          - |
            /scripts/prepare-tap.sh -a "2.2.2.2/32" -o
            nc -lk "2.2.2.2" "53" &
            sleep 2
            while sleep 30; do nc -zv "2.2.2.2" "53"; done
        command:
        - /bin/bash
        - -c
        image: quay.io/jvirtane/external-connection:4.8.x-619-g1fb6d87786-dirty-4
        imagePullPolicy: IfNotPresent
        name: external-destination-source
        resources: {}
        securityContext:
          capabilities: {}
          privileged: true
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
