apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: dynamic-connector
    name: dynamic-connector
  name: dynamic-connector
  namespace: qa
spec:
  minReadySeconds: 15
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dynamic-connector
      name: dynamic-connector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dynamic-connector
        deployment: dynamic-connector
        name: dynamic-connector
      name: dynamic-connector
      namespace: qa
    spec:
      imagePullSecrets:
        - name: qa
      containers:
      - image: quay.io/jvirtane/dynamic-connector:4.8.x-909-gd5216e5572
        imagePullPolicy: IfNotPresent
        name: dynamic-connector
        resources: {}
        securityContext:
          capabilities: {}
          privileged: true
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
